# Generated by Django 6.0.6 on 2026-06-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='committee/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Committee Member',
                'verbose_name_plural': 'Committee Members',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purpose', models.CharField(choices=[('General Church Fund', 'General Church Fund'), ('Building Maintenance', 'Building Maintenance'), ('Sunday School', 'Sunday School'), ('Youth Ministry (OCYM)', 'Youth Ministry (OCYM)'), ('Social Service / Charity', 'Social Service / Charity'), ('Feast Day Offering', 'Feast Day Offering'), ('Priest Support Fund', 'Priest Support Fund'), ('Memorial / Thanksgiving', 'Memorial / Thanksgiving')], default='General Church Fund', max_length=100)),
                ('gateway', models.CharField(choices=[('razorpay', 'Razorpay'), ('payu', 'PayU'), ('paytm', 'Paytm'), ('upi', 'UPI Direct')], default='razorpay', max_length=20)),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('transaction_id', models.CharField(blank=True, max_length=200)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('donated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-donated_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Feast Day', 'Feast Day'), ('Major Feast', 'Major Feast'), ('Youth', 'Youth'), ('Education', 'Education'), ('Fellowship', 'Fellowship'), ('Community', 'Community'), ('Other', 'Other')], default='Other', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('completed', 'Completed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=300)),
                ('event_name', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(upload_to='gallery/')),
                ('icon', models.CharField(default='⛪', max_length=10)),
                ('bg_color', models.CharField(default='linear-gradient(135deg,#1B4332,#2D6A4F)', max_length=80)),
                ('order', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Gallery Photo',
                'verbose_name_plural': 'Gallery Photos',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('founded', models.IntegerField(blank=True, null=True)),
                ('leader', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='✝️', max_length=10)),
                ('bg_color', models.CharField(default='rgba(82,121,111,0.15)', max_length=60)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('praying', 'Praying'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('admin_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Prayer Request',
                'verbose_name_plural': 'Prayer Requests',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('query_type', models.CharField(choices=[('General Query', 'General Query'), ('Sacrament Enquiry', 'Sacrament Enquiry (Baptism, Marriage, etc.)'), ('Pastoral Counselling', 'Pastoral Counselling'), ('Membership / Transfer', 'Membership / Transfer'), ('Donation Enquiry', 'Donation Enquiry'), ('Other', 'Other')], default='General Query', max_length=100)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('admin_response', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Query',
                'verbose_name_plural': 'Queries',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('day', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Daily', 'Daily')], max_length=20)),
                ('time', models.TimeField()),
                ('location', models.CharField(default='Main Sanctuary', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service Timing',
                'verbose_name_plural': 'Service Timings',
                'ordering': ['day', 'time'],
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_headline', models.CharField(default='Where Faith Meets Fellowship', max_length=300)),
                ('hero_subtext', models.TextField(default='Gathered in the name of Christ, rooted in the ancient Orthodox tradition.')),
                ('church_address', models.CharField(default='Tiruvalla - Vennikulam - Ranni Rd, Kavungumprayar Puramattam, Kerala 689544', max_length=400)),
                ('phone', models.CharField(default='0469 2750591', max_length=30)),
                ('email', models.EmailField(default='info@stthomaskottayam.org', max_length=254)),
                ('youtube_link', models.URLField(blank=True)),
                ('history_summary', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Content',
                'verbose_name_plural': 'Site Content',
            },
        ),
        migrations.CreateModel(
            name='SundayReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('lesson1', models.CharField(blank=True, max_length=200)),
                ('lesson2', models.CharField(blank=True, max_length=200)),
                ('gospel', models.CharField(blank=True, max_length=200)),
                ('epistle', models.CharField(blank=True, max_length=200)),
                ('hymn1', models.CharField(blank=True, max_length=50, verbose_name='Opening Hymn 1 No.')),
                ('hymn2', models.CharField(blank=True, max_length=50, verbose_name='Opening Hymn 2 No.')),
                ('offertory', models.CharField(blank=True, max_length=50, verbose_name='Offertory Song No.')),
                ('communion', models.CharField(blank=True, max_length=50, verbose_name='Communion Hymn No.')),
                ('live_info', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sunday Reading',
                'verbose_name_plural': 'Sunday Readings',
                'ordering': ['-date'],
            },
        ),
    ]
