# Generated by Django 4.0.4 on 2026-06-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='committeemember',
            options={},
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='committee_members/'),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='role',
            field=models.CharField(max_length=100),
        ),
    ]
