# Generated by Django 4.0.4 on 2026-06-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_committeemember_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryphoto',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='galleryphoto',
            old_name='photo',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='galleryphoto',
            name='bg_color',
        ),
        migrations.RemoveField(
            model_name='galleryphoto',
            name='icon',
        ),
        migrations.AddField(
            model_name='galleryphoto',
            name='redirect_url',
            field=models.URLField(blank=True, help_text='URL to open when the image is clicked'),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='caption',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
