# Generated by Django 4.0.4 on 2026-06-24 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_organizationtiming'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={},
        ),
        migrations.RemoveField(
            model_name='organization',
            name='bg_color',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='icon',
        ),
        migrations.AddField(
            model_name='organization',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='organizations/'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='organization',
            name='founded',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='leader',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
