# Generated by Django 4.0.4 on 2026-06-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('tenure', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='priests/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
